### ISSUE TITLE
Use EncodeUri() if part of the URL path or EncodeUriComponent() if used as a URL parameter

### ISSUE THREAD

**Issue by semisight** [stape-io/supabase-writer-tag#1]
https://github.com/stape-io/supabase-writer-tag/blob/5731b7181e514cfb7869f4109cac6708ca2eaada/template.tpl#L159

When reviewing your template we've noticed that it is using parameters to build a url. It's a best practice to use [EncodeUri()](https://developers.google.com/tag-manager/templates/api#encodeuri) if part of the URL path or [EncodeUriComponent()](https://developers.google.com/tag-manager/templates/api#encodeuricomponent) if used as a URL parameter.

**Comment by Bukashk0zzz** [comment]
Thanks.
It's fixed now https://github.com/stape-io/supabase-writer-tag/commit/b3c7e86a9260fa3053fe4371e88ec0a8df6add9d
